version: "3.8"

services:
  database:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: "always"
    volumes:
      - ${POSTGRES_VOLUMES}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: host
  app:
    build: .
    container_name: ${PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
    network_mode: host
    links:
      - database
    depends_on:
      - database
