version: "3.8"

services:
  database:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: "always"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: "always"
    ports:
      - ${REDIS_PORT}:6379

volumes:
  pg_data:
    driver: local
