@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=specifications

@token_admin_seed={{$dotenv TOKEN_SEED_ADMIN}}
@token_invalid=eyJhbGciOiJIUzI1NiIs.eyJTgtMzEzMS0M2FjLThkM.QKsAcSaTgOS8PG32txDqH

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Câmbio automático",
  "description": "Especificação de carro com câmbio automático"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Teto solar",
  "description": "Especificação de carro com teto solar"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "4 portas",
  "description": "Especificação de carro com 4 portas"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "2 portas",
  "description": "Especificação de carro com 2 portas"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "piloto automático",
  "description": "Especificação de carro com piloto automático"
}

### Create specification invalid token
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_invalid}}
Content-Type: application/json

{
  "name": "Invalid token",
  "description": "Especificação de Invalid token"
}
