@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=specifications

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY5OTYxODgsImV4cCI6MTYzNzA4MjU4OCwic3ViIjoiMzEyYTQyNDEtOWIxMC00OGViLWJjMDEtMWE2YzFjYmYxOGJiIn0.8f5HuFe_dZVxCb_C-ntOiu291wdaVAwndMsfNgZ0B28
@token_invalid=eyJhbGciOiJIUzI1NiIs.eyJTgtMzEzMS00M2FjLThkM.QKsAcSaTgoxOS8PG32txDqH

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Câmbio automático",
  "description": "Especificação de carro com câmbio automático"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Teto solar",
  "description": "Especificação de carro com teto solar"
}

### Create specification
POST {{url_base}}/{{path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "4 portas",
  "description": "Especificação de carro com 4 portas"
}

### Create specification invalid token
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_invalid}}
Content-Type: application/json

{
  "name": "Invalid token",
  "description": "Especificação de Invalid token"
}
