@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=users/avatar

@token_admin_seed={{$dotenv TOKEN_SEED_ADMIN}}
@token_invalid=nR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzYNDYsImV4cCI6.NVUZVgs2GmeCYZcqpagr


### Import avatar
PATCH  {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar3.jpg"
Content-Type: image/png

< /home/marcelo/Downloads/avatar/avatar3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Import avatar with invalid token
PATCH  {{url_base}}/{{path}}
Authorization: Bearer {{token_invalid}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar3.jpg"
Content-Type: image/png

< /home/marcelo/Downloads/avatar/avatar3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
