@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=refresh-token

### Create refresh token User Admin Seed
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNjM4Mzc1OTgwLCJleHAiOjE2NDA5Njc5ODAsInN1YiI6ImFhZDE2NjNmLTRhMWYtNDQ1ZS04YTk2LWYzNjkyNmU0MmZjNyJ9.MgZCWrcqXurZZq8OZ82UpSc1T_hY_xmAqHFTM9kL39k"
}
