@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=sessions

### Create token user1
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "1234"
}

### Create token user2
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user2@mail.com",
  "password": "1234"
}

### Create token user3
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user3@mail.com",
  "password": "1234"
}

### Create token user4
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user4@mail.com",
  "password": "1234"
}

### Create token user5
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user5@mail.com",
  "password": "1234"
}

### Create token with incorrect email
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user1000@mail.com",
  "password": "1234"
}

### Create token with incorrect password
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "email": "user1@mail.com",
  "password": "4321"
}
