@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=cars
@token_admin_seed={{$dotenv TOKEN_SEED_ADMIN}}
@token_not_admin=eyJhbGciOiJIUzI1NCJ9.eyJpYXQiO2MzcyYzNzM2N.Jr7RDtrD763vCANodTup

### Create car Audi A3
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "A3",
  "description": "carro sedã 4 portas",
  "daily_rate": "500",
  "license_plate": "XPT-0000",
  "fine_amount": "350",
  "brand": "Audi",
  "category_id": "c0b0c58c-dc77-49bc-ab9e-ffb7d480fb61"
}

### Create car Audi A4
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "A4",
  "description": "carro sedã 4 portas",
  "daily_rate": "500",
  "license_plate": "AAA-0004",
  "fine_amount": "350",
  "brand": "Audi",
  "category_id": "c0b0c58c-dc77-49bc-ab9e-ffb7d480fb61"
}

### Create car Fusca
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Fusca",
  "description": "carro popular 2 portas",
  "daily_rate": "100",
  "license_plate": "FUS-0001",
  "fine_amount": "50",
  "brand": "Volkswagen",
  "category_id": "f793a2dc-4d58-43ef-b485-12b06b538ab4"
}


### Create car Jetta
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Jetta",
  "description": "carro sedã 4 portas",
  "daily_rate": "100",
  "license_plate": "JET-0001",
  "fine_amount": "50",
  "brand": "Volkswagen",
  "category_id": "c0b0c58c-dc77-49bc-ab9e-ffb7d480fb61"
}

### Create car user not admin
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_not_admin}}
Content-Type: application/json

{
  "name": "Any",
  "description": "any description",
  "daily_rate": "100",
  "license_plate": "FUS-0001",
  "fine_amount": "50",
  "brand": "",
  "category_id": "9722e841-d8a1-4e0c-a2d5-1be75deb0cdc"
}
