@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=password/reset

@token=dbdb3004-75f0-4851-a5bd-3838d5063ab6


# @url=http://localhost:3333/password/reset?token=7dde8eb0-8bdb-4329-a226-bd7e1a7030db


### Reset password
POST {{url_base}}/{{path}}?token={{token}}
# POST {{url}}
Content-Type: application/json

{
  "password": "1234"
}
