@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=categories

@token_admin_seed={{$dotenv TOKEN_SEED_ADMIN}}

### Create category Pick-Up
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Pick-Up",
  "description": "Categoria de carro utilitário"
}

### Create category Van
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Van",
  "description": "Categoria de carro de utilitário"
}
