@host={{$dotenv SERVER_HOST}}
@port={{$dotenv SERVER_PORT}}
@url_base=http://{{host}}:{{port}}
@path=categories

@token_admin_seed=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzczMTkyNjcsImV4cCI6MTYzNzQwNTY2Nywic3ViIjoiM2FkYzJiMWYtN2UxMS00MGRlLThlYjUtNWZkZWM3MWE4Yjc5In0.TmgB4IGfrbphRj7ARY4FQG2ODmmCGEPtL0-SpJNpptA

### Create category Pick-Up
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Pick-Up",
  "description": "Categoria de carro utilitário"
}

### Create category Van
POST {{url_base}}/{{path}}
Authorization: Bearer {{token_admin_seed}}
Content-Type: application/json

{
  "name": "Van",
  "description": "Categoria de carro de utilitário"
}
